version: '3'
services:

  mongo-database:
    container_name: ps-mongo
    image: mongo
    ports:
    - "27017:27017"

  redis:
    container_name: ps-redis
    image: redis
    ports:
    - "6379:6379"

  admin:
    container_name: ps-admin
    image: price-admin:latest        
    ports:
    - "5000:5000"        
    environment:
    - ASPNETCORE_ENVIRONMENT=local
    - ASPNETCORE_URLS=http://+:5000
    - Storage:ConnectionString=mongodb://ps-mongo:27017/price
    links:
    - "mongo-database:database"

  api:
    container_name: ps-api
    image: price-api:latest
    ports:
    - "4772:4772"
    environment:
    - ASPNETCORE_ENVIRONMENT=local
    - ASPNETCORE_URLS=http://*:4772
    - BindingPort=4772
    - Storage:ConnectionString=mongodb://ps-mongo:27017/price
    - Redis:Configuration=ps-redis:6379
    - Kafka:Bootstrap=kafka-bootstrap.k8s-stg2.datalake.central.tech:443
    - Kafka:SslCaLocation=DevKeys/truststore.cer.pem
    - Kafka:SslCertificateLocation=DevKeys/keystore.crt
    - Kafka:SslKeyLocation=DevKeys/keystore.key
    - MessageBus:PriceImport=push.products.price.updated-test-local
    volumes:
    - ./DevKeys:/app/DevKeys
    links:
    - "mongo-database:database"

  scheduler:
    container_name: ps-scheduler
    image: price-scheduler:latest        
    ports:
    - "5005:5005"        
    environment:
    - ASPNETCORE_ENVIRONMENT=local
    - ASPNETCORE_URLS=http://*:5005
    - Storage:ConnectionString=mongodb://ps-mongo:27017/price
    - Redis:Configuration=ps-redis:6379
    - ActorSystem:Seeds=akka.tcp://price-service@localhost:5005
    - Kafka:Bootstrap=kafka-bootstrap.k8s-stg2.datalake.central.tech:443
    - Kafka:SslCaLocation=DevKeys/truststore.cer.pem
    - Kafka:SslCertificateLocation=DevKeys/keystore.crt
    - Kafka:SslKeyLocation=DevKeys/keystore.key
    - MessageBus:PriceImport=push.products.price.updated-test-local
    - MessageBus:PriceAnnouncement=push.price.service.updated-test-local
    volumes:
    - ./DevKeys:/app/DevKeys
    links:
    - "mongo-database:database"